### ISSUE TITLE
Error reading tags

### ISSUE THREAD

**Issue by nullvalue0** [martinpaljak/nfc4pc#9]
Seems regardless of the tag type I use (tried with Classic 1K, NTAG213 and NTAG424), I get the following error as soon as I tap it:

22:40:44:508 [ACS ACR122 0] [ERROR] NFCReader - Could not connect to or read: newPosition < 0: (-2 < 0)
java.lang.IllegalArgumentException: newPosition < 0: (-2 < 0)
        at java.base/java.nio.Buffer.createPositionException(Buffer.java:341)
        at java.base/java.nio.Buffer.position(Buffer.java:316)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1516)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmitImpl(Smartcardio.java:809)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmit(Smartcardio.java:690)
        at apdu4j.pcsc.CardBIBO.transceive(CardBIBO.java:130)
        at apdu4j.core.APDUBIBO.transmit(APDUBIBO.java:35)
        at pro.javacard.nfc4pc.NDEF.getType2(NDEF.java:42)
        at pro.javacard.nfc4pc.NFCReader.tryToRead(NFCReader.java:120)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
WARNING: Could not read: newPosition < 0: (-2 < 0)

I am using a ACR-122U reader. What could be causing this?

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/NFC4PC/wiki/Supported-readers
get a different reader. See a similar issue: https://github.com/martinpaljak/GlobalPlatformPro/issues/307
